import { Theme } from '../types/game'
export const themes: Record<string, Theme> = {
  default: {
    id: 'default',
    name: "Predeterminado",
    background: 'bg-gradient-to-br from-indigo-900 via-purple-900 to-pink-900',
    playerX: 'text-blue-400',
    playerO: 'text-red-400',
    boardBg: 'bg-white/5',
    cellBg: 'bg-white/10',
    textColor: 'text-white'
  },
  retro: {
    id: 'retro',
    name: 'Konami',
    background: 'bg-gradient-to-br from-green-900 via-green-800 to-green-900',
    playerX: 'text-green-400',
    playerO: 'text-yellow-400',
    boardBg: 'bg-black/50',
    cellBg: 'bg-black/30',
    textColor: 'text-green-400'
  },
  neon: {
    id: 'neon',
    name: 'Neón',
    background: 'bg-gradient-to-br from-purple-900 via-pink-900 to-purple-900',
    playerX: 'text-cyan-400',
    playerO: 'text-pink-400',
    boardBg: 'bg-black/50',
    cellBg: 'bg-black/30',
    textColor: 'text-white'
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    background: 'bg-[conic-gradient(at_bottom_left,_var(--tw-gradient-stops))] from-yellow-500 via-purple-600 to-cyan-500',
    playerX: 'text-yellow-300',
    playerO: 'text-cyan-300',
    boardBg: 'bg-purple-900/70',
    cellBg: 'bg-purple-800/50',
    textColor: 'text-yellow-200'
  },
  nature: {
    id: 'nature',
    name: 'Naturalista',
    background: 'bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-green-600 via-emerald-500 to-teal-400',
    playerX: 'text-emerald-300',
    playerO: 'text-teal-200',
    boardBg: 'bg-green-900/30',
    cellBg: 'bg-green-800/20',
    textColor: 'text-emerald-100'
  },
  sunset: {
    id: 'sunset',
    name: 'Atardecer',
    background: 'bg-[conic-gradient(at_top,_var(--tw-gradient-stops))] from-orange-500 via-red-500 to-purple-600',
    playerX: 'text-orange-300',
    playerO: 'text-purple-300',
    boardBg: 'bg-red-900/30',
    cellBg: 'bg-red-800/20',
    textColor: 'text-orange-100'
  },
  galaxy: {
    id: 'galaxy',
    name: 'Galáctico',
    background: 'bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-blue-700 via-indigo-900 to-purple-900',
    playerX: 'text-blue-300',
    playerO: 'text-purple-300',
    boardBg: 'bg-indigo-900/30',
    cellBg: 'bg-indigo-800/20',
    textColor: 'text-blue-100'
  },
  candy: {
    id: 'candy',
    name: 'Acaramelado',
    background: 'bg-gradient-to-br from-pink-500 via-red-400 to-yellow-400',
    playerX: 'text-pink-300',
    playerO: 'text-yellow-300',
    boardBg: 'bg-pink-900/30',
    cellBg: 'bg-pink-800/20',
    textColor: 'text-pink-100'
  },
  thanksgiving: {
    id: 'thanksgiving',
    name: 'Acción de Gracias',
    background: 'bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-orange-600 via-yellow-400 to-brown-800',
    playerX: 'text-orange-200',
    playerO: 'text-yellow-200',
    boardBg: 'bg-[rgba(255,255,255,0.2)] backdrop-blur-md border border-orange-200 rounded-lg',
    cellBg: 'bg-[rgba(255,255,255,0.1)] rounded-md shadow-lg',
    textColor: 'text-white',
  },
  halloween: {
    id: 'halloween',
    name: 'Día de Brujas',
    background: 'bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-purple-800 via-black to-orange-600',
    playerX: 'text-purple-300 shadow-lg glow-purple',
    playerO: 'text-orange-400 shadow-lg glow-orange',
    boardBg: 'bg-[rgba(0,0,0,0.5)] backdrop-blur-md border border-purple-500 rounded-lg',
    cellBg: 'bg-[rgba(255,165,0,0.2)] rounded-md shadow-xl hover:bg-orange-500/30 transition duration-300 ease-in-out transform hover:scale-105',
    textColor: 'text-white',
  },
  christmas: {
    id: 'christmas',
    name: 'Navidad',
    background: 'bg-gradient-to-br from-red-600 via-red-500 to-green-400',
    playerX: 'text-red-900 font-extrabold shadow-lg',
    playerO: 'text-green-900 font-extrabold shadow-lg',
    boardBg: 'bg-white/30 backdrop-blur-md border-4 border-red-800 rounded-lg shadow-xl',
    cellBg: 'bg-red-200 hover:bg-red-300 transition duration-300 ease-in-out rounded-md',
    textColor: 'text-gray-800 font-semibold',
  },
  tropical: {
    id: 'tropical',
    name: 'Fiesta Tropical',
    background: 'bg-[radial-gradient(circle,_rgba(255,204,0,_0.6),_rgba(255,85,0,_0.6),_rgba(255,0,150,_0.6))] bg-cover',
    playerX: 'text-yellow-500 font-extrabold shadow-lg',
    playerO: 'text-pink-500 font-extrabold shadow-lg',
    boardBg: 'bg-[conic-gradient(from_180deg,_rgba(255,255,255,0.1),_rgba(255,255,255,0.3))] border-4 border-orange-600 rounded-lg shadow-xl',
    cellBg: 'bg-orange-300 hover:bg-orange-400 transition duration-300 ease-in-out rounded-md',
    textColor: 'text-gray-900 font-semibold',
  },
  medieval: {
    id: 'medieval',
    name: 'Época Medieval',
    background: 'bg-gradient-to-br from-gray-900 via-gray-800 to-gray-700',
    playerX: 'text-yellow-500 font-extrabold shadow-lg hover:scale-110 transition-transform duration-300 ease-in-out',
    playerO: 'text-red-600 font-extrabold shadow-lg hover:scale-110 transition-transform duration-300 ease-in-out',
    boardBg: 'bg-gray-950/80 backdrop-blur-md border-4 border-gold-500 rounded-lg shadow-xl',
    cellBg: 'bg-gray-800 hover:bg-gray-700 transition duration-300 ease-in-out rounded-md shadow-md transform hover:translate-y-1',
    textColor: 'text-white font-semibold text-shadow-lg',
  },
  space: {
    id: 'space',
    name: 'Espacio Sideral',
    background: 'bg-[radial-gradient(circle,_rgba(0,0,0,0.8),_rgba(0,0,0,1))] bg-cover',
    playerX: 'text-blue-400 font-bold shadow-lg hover:scale-110 transition-transform duration-300 ease-in-out',
    playerO: 'text-purple-500 font-bold shadow-lg hover:scale-110 transition-transform duration-300 ease-in-out',
    boardBg: 'bg-[conic-gradient(from_180deg,_rgba(255,255,255,0.1),_rgba(255,255,255,0.3))] border-4 border-blue-600 rounded-lg shadow-xl animate-pulse',
    cellBg: 'bg-[radial-gradient(circle,_rgba(255,255,255,0.1),_rgba(0,0,0,0.5))] hover:bg-[radial-gradient(circle,_rgba(255,255,255,0.2),_rgba(0,0,0,0.6))] transition duration-300 ease-in-out rounded-md shadow-md transform hover:translate-y-1',
    textColor: 'text-white font-semibold text-shadow-lg',
  },
}